Repository dondakeshimo/todo-cli, pull requests merged in 2021-03, with the labels that each got.

#53 refactor: 値オブジェクトの使用 / gateways/jsonの追加
  internal/commands/add.go
  internal/commands/close.go
  internal/commands/list.go
  internal/commands/modify.go
  internal/commands/notify.go
  internal/commands/utils.go
  internal/entities/reminder/reminder.go
  internal/entities/reminder/reminder_test.go
  internal/entities/remindtime/relative_time.go
  internal/entities/remindtime/relative_time_test.go
  internal/entities/remindtime/remind_time.go
  internal/entities/remindtime/remind_time_test.go
  internal/entities/task/task.go
  internal/entities/task/task_handler.go
  internal/entities/task/task_handler_test.go
  internal/entities/task/task_test.go
  internal/entities/timestr/timestr.go
  internal/entities/timestr/timestr_test.go
  internal/gateways/json/task_repository.go
Labels: ready in review

#57 RemoveTaskの修正
  internal/entities/task/task_handler.go
  internal/entities/task/task_handler_test.go
Labels: bug, ready in review

#64 release ジョブの修正
  .github/workflows/release.yml
  CHANGELOG.md
Labels: work in progress

#30 シナリオテストを作った
  .github/workflows/go.yml
  Makefile
  test/scenario/crud_test.go
  test/scenario/main_test.go
Labels: ready in review

#56 readmeの整備
  README.md
Labels: ready in review

#69 Actionとgifとhelpの修正
  .github/workflows/go.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/release.yml
  README.md
  cmd/todo/main.go
Labels: ready in review

#71 Release/v0.1.0
  CHANGELOG.md
  README.md
  cmd/todo/main.go
Labels: release

#73 Add dependency in Makefile for calling build before testing
  Makefile
Labels: ready in review

#72 Add priority feature
  cmd/todo/main.go
  internal/commands/add.go
  internal/commands/list.go
  internal/commands/modify.go
  internal/entities/task/task.go
  internal/entities/task/task_handler.go
  internal/entities/task/task_handler_test.go
  internal/entities/task/task_test.go
  internal/gateways/json/task_repository.go
  test/scenario/crud_test.go
Labels: ready in review

#74 Use tabwriter modified for CJK instead of text/tabwriter
  go.mod
  go.sum
  internal/commands/list.go
  pkg/writer/writer.go
  test/scenario/crud_test.go
Labels: ready in review

#75 Release/0.2.0
  CHANGELOG.md
Labels: release
